"""Generate the OCR test fixtures in `app/src/androidTest/assets/`.

These are **generated** images — clean, high-contrast text on a plain ground,
which is the easy case for a recognizer. They prove that the pipeline is wired
up and that our own bookkeeping is coherent. They deliberately do not prove
accuracy on real signage; that needs photographs (V-10, V-26).

The value of a generated fixture is that the *correct answer is known exactly*.
`sign-vertical.png` writes the same two lines as `sign-horizontal.png`, so both
must recognize to the same string. Any difference is ML Kit's handling of
縦書き, not a difference in the content.

Run from this directory:

    python make_fixtures.py

`sign-horizontal.png` predates this script and is not regenerated by it — the
committed file is what the existing Phase 4 tests assert against, and there is
nothing to gain from perturbing it.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ASSETS = Path(__file__).resolve().parents[2] / "app" / "src" / "androidTest" / "assets"

# Sampled from sign-horizontal.png so the fixtures look like one set.
BACKGROUND = (250, 248, 243)
INK = (18, 16, 14)

FONT = "C:/Windows/Fonts/YuGothR.ttc"


def vertical_sign(stagger: bool = False) -> Image.Image:
    """Two 縦書き columns, read right-to-left, top-to-bottom.

    The content is deliberately identical to `sign-horizontal.png`, so the
    expected recognition is the same string: 先生と生産, then 東京都の学生.

    That makes every failure mode distinguishable from the string alone:

    | Recognized                | Means                                    |
    |---------------------------|------------------------------------------|
    | 先生と生産 / 東京都の学生 | columns ordered right-to-left — correct  |
    | 東京都の学生 / 先生と生産 | columns ordered left-to-right — reversed |
    | 先東京生都...             | rows read across columns — interleaved   |

    A test can therefore tell *how* the reading order is wrong, not merely that
    it is, which is what decides where the fix belongs (stage 2 or stage 4).

    With ``stagger``, the right-hand column starts well above the left-hand one
    instead of level with it. Level columns cannot distinguish "ordered
    left-to-right" from "ordered top-to-bottom, ignoring columns", because both
    put the left column first when the two tops are within a pixel or two of each
    other. Staggering separates them: a recognizer sorting by y now emits the
    right column first, one sorting by x still emits the left column first.
    """
    width, height = 900, (1450 if stagger else 1100)
    image = Image.new("RGB", (width, height), BACKGROUND)
    draw = ImageDraw.Draw(image)

    size = 110
    font = ImageFont.truetype(FONT, size)
    advance = int(size * 1.18)  # Vertical rhythm: CJK glyphs are square, so this
                                # is close to the em box plus a little air.

    # Rightmost column is read first.
    columns = ["先生と生産", "東京都の学生"]
    column_gap = int(size * 1.75)
    right_edge = width - int(size * 1.3)
    top = int(size * 0.7)

    # Rightmost column high, leftmost column low, so y-order and x-order disagree.
    tops = [top, top + int(size * 2.6)] if stagger else [top, top]

    for column_index, column in enumerate(columns):
        centre_x = right_edge - column_index * column_gap
        column_top = tops[column_index]
        for char_index, char in enumerate(column):
            # Centre each glyph on the column axis. CJK glyphs are uniformly
            # wide, but the measured ink box is not — centring on the drawn
            # bounds rather than the advance keeps the column edges straight,
            # which is the signal stage 4 will read to find the column.
            left, _, right, _ = font.getbbox(char)
            x = centre_x - (left + right) / 2
            draw.text((x, column_top + char_index * advance), char, font=font, fill=INK)

    return image


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    for name, image in (
        ("sign-vertical.png", vertical_sign()),
        ("sign-vertical-staggered.png", vertical_sign(stagger=True)),
    ):
        out = ASSETS / name
        image.save(out)
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
