package com.spotterkanji.app.scan

import android.graphics.BitmapFactory
import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.spotterkanji.domain.scan.ScanLayout
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * 縦書き reads right to left, end to end and against the real recognizer (V-10).
 *
 * **This file previously asserted the opposite.** It was written to pin ML Kit's
 * own behaviour — columns emitted left to right — which D-75 measured and D-76
 * decided how to fix. Now that `:domain` imposes the reading order, the same
 * fixtures must come back in the right order, and the characterization tests
 * have been replaced by the assertions they were standing in for. That inversion
 * was predicted in the original commit; if it ever needs inverting back,
 * something has regressed rather than improved.
 *
 * The unit-level cases live in `:domain` (`ScanLayoutTest`, `RealNoticeLayoutTest`)
 * where they cost seconds. What is left here is the part only a device can
 * answer: that the real ML Kit output, fed through the real conversion, arrives
 * at the same result.
 *
 * Fixtures are generated by `tools/fixtures/make_fixtures.py`.
 */
@RunWith(AndroidJUnit4::class)
class VerticalTextOrderTest {

    private val context = InstrumentationRegistry.getInstrumentation().context

    private fun recognize(name: String): ScanLayout {
        val bitmap = context.assets.open(name).use { BitmapFactory.decodeStream(it) }
        val recognizer = JapaneseTextRecognizer()
        return try {
            runBlocking { recognizer.recognize(bitmap) }
        } finally {
            recognizer.close()
        }
    }

    private fun report(name: String, layout: ScanLayout): String = buildString {
        appendLine("=== $name ===")
        appendLine("text: ${layout.text.replace("\n", " / ")}")
        appendLine("placements: ${layout.placements.size}")
    }.also { Log.i(TAG, it) }

    /**
     * The rightmost column is read first.
     *
     * Asserted on column *order* rather than on string equality with the
     * horizontal fixture, because ML Kit misreads 都 on both vertical fixtures
     * (D-75) and pinning that would make this a test of the model's accuracy
     * rather than of our geometry. The order is ours; the glyph is not.
     */
    @Test
    fun vertical_columns_are_read_right_to_left() {
        val layout = recognize("sign-vertical.png")
        val text = report("vertical", layout)

        val rightColumn = layout.text.indexOf("先生と生産")
        val leftColumn = layout.text.indexOf("学生")

        assertTrue("expected 先生と生産 somewhere in\n$text", rightColumn >= 0)
        assertTrue("expected the left column somewhere in\n$text", leftColumn >= 0)
        assertTrue(
            "the rightmost column must be read first — 縦書き runs right to left\n$text",
            rightColumn < leftColumn,
        )
    }

    /** The same, when the columns do not begin level. */
    @Test
    fun staggered_columns_are_still_read_right_to_left() {
        val layout = recognize("sign-vertical-staggered.png")
        val text = report("vertical-staggered", layout)

        val rightColumn = layout.text.indexOf("先生と生産")
        val leftColumn = layout.text.indexOf("学生")

        assertTrue("expected 先生と生産 somewhere in\n$text", rightColumn >= 0)
        assertTrue(
            "column order must not depend on how the columns line up\n$text",
            rightColumn in 0..<leftColumn,
        )
    }

    /**
     * The two columns are separate lines of a sign, not one flow, so a word must
     * not be invented across the boundary (V-28).
     */
    @Test
    fun the_two_columns_are_kept_apart() {
        val layout = recognize("sign-vertical.png")
        val text = report("vertical", layout)

        assertEquals(
            "expected exactly one separator, between the two columns\n$text",
            1,
            layout.text.count { it == '\n' },
        )
    }

    @Test
    fun horizontal_text_is_unaffected() {
        val layout = recognize("sign-horizontal.png")
        val text = report("horizontal", layout)

        assertEquals("先生と生産\n東京都の学生", layout.text)
        assertTrue(text.isNotEmpty())
    }

    /**
     * The bookkeeping invariant everything downstream rests on, checked against
     * real recognizer output rather than hand-written boxes: a placement's
     * offset must address its own character.
     */
    @Test
    fun every_placement_addresses_its_own_character() {
        for (fixture in listOf(
            "sign-horizontal.png",
            "sign-vertical.png",
            "sign-vertical-staggered.png",
        )) {
            val layout = recognize(fixture)
            assertTrue("nothing recognized in $fixture", layout.placements.isNotEmpty())
            for (placement in layout.placements) {
                assertEquals(
                    "in $fixture, offset ${placement.offset} should hold '${placement.char}'",
                    placement.char,
                    layout.text[placement.offset],
                )
            }
        }
    }

    private companion object {
        const val TAG = "VerticalTextOrder"
    }
}
