package com.spotterkanji.app.scan

import android.graphics.BitmapFactory
import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * **What ML Kit does with 縦書き** (V-10). Measured 2026-08-26.
 *
 * This gated the stage 4 design and was the first thing Phase 5 did, before any
 * coordinate work. Stage 2 took ML Kit's own block-then-line order as given and
 * concatenated it ([RecognizedText]), so if the recognizer walked columns
 * left-to-right the string would be **scrambled before stage 4 saw a pixel** — a
 * stage 2 fault wearing a stage 4 costume, and a different fix in a different
 * file.
 *
 * **It does walk them left-to-right.** These tests pin that, because it is not
 * visible in any other way: nothing errors, every column is individually
 * correct, and the defect only shows as a *sequence*.
 *
 * What was measured, on fixtures whose correct answer is known exactly:
 *
 * | Behaviour                                   | Verdict                     |
 * |---------------------------------------------|-----------------------------|
 * | Within a column, top-to-bottom              | **Correct**                 |
 * | Each column grouped as one line             | **Correct** — separator lands between columns |
 * | Column order                                | **Backwards** — left-to-right, not right-to-left |
 * | Column order when columns are staggered in y | Still left-to-right — so it is an x-sort, not a y-sort |
 * | Elements per column                         | **Unstable** — one column can arrive as several elements |
 *
 * The last two are the ones that shaped the design. Stagger does not perturb the
 * order at all, so this is not a position sort that vertical text happens to
 * confuse — it is a horizontal-text assumption applied unconditionally, and it
 * will never come out right on its own. And because elements split mid-column,
 * nothing downstream may assume one element per line.
 *
 * **Consequence:** the reordering belongs in stage 2, before concatenation,
 * because the concatenation is what defines the offsets. Note that taps would
 * nonetheless resolve *correctly* today — each element carries its own box and
 * its own offset, and the two agree — so what is broken is the flow, not the
 * mapping. The flow becomes load-bearing the moment V-28 lets two lines join.
 *
 * Fixtures are generated by `tools/fixtures/make_fixtures.py`.
 */
@RunWith(AndroidJUnit4::class)
class VerticalTextOrderTest {

    private val context = InstrumentationRegistry.getInstrumentation().context

    private fun recognize(name: String): RecognizedText {
        val bitmap = context.assets.open(name).use { BitmapFactory.decodeStream(it) }
        val recognizer = JapaneseTextRecognizer()
        return try {
            runBlocking { recognizer.recognize(bitmap) }
        } finally {
            recognizer.close()
        }
    }

    /**
     * Dumps the whole of stage 2's output, so a change in ML Kit's behaviour can
     * be read off a failing run rather than re-derived from scratch.
     */
    private fun dump(name: String, result: RecognizedText): String = buildString {
        appendLine("=== $name ===")
        appendLine("text: ${result.text.replace("\n", "\\n")}")
        appendLine("elements: ${result.elements.size}")
        result.elements.forEach { element ->
            appendLine(
                "  '${element.text}' @${element.startOffset}..${element.endOffset} " +
                    "box=${element.box.left},${element.box.top}," +
                    "${element.box.right},${element.box.bottom} " +
                    "(${element.box.width()}x${element.box.height()})",
            )
        }
    }.also { Log.i(TAG, it) }

    /**
     * Each column is read top-to-bottom correctly, and each is grouped as one
     * line — so the line separator lands between the columns, where it belongs.
     *
     * This is the good news, and it is what makes the fix a **reorder** rather
     * than a reconstruction: the groups are right, only their sequence is wrong.
     */
    @Test
    fun within_a_column_the_reading_order_is_correct() {
        val result = recognize("sign-vertical.png")
        val report = dump("vertical", result)

        assertTrue(
            "expected the right-hand column read top-to-bottom as 先生と生産\n$report",
            result.text.contains("先生と生産"),
        )
        assertEquals(
            "expected exactly one separator, between the two columns\n$report",
            1,
            result.text.count { it == '\n' },
        )
    }

    /**
     * **The defect.** 縦書き reads right-to-left, so the rightmost column comes
     * first. ML Kit emits the leftmost column first.
     *
     * The fixture writes the same two lines as `sign-horizontal.png`, one per
     * column, so the correct recognition is the same string. It is not.
     */
    @Test
    fun columns_are_emitted_left_to_right_which_is_backwards() {
        val horizontal = recognize("sign-horizontal.png")
        val vertical = recognize("sign-vertical.png")
        val report = dump("horizontal", horizontal) + "\n" + dump("vertical", vertical)

        val leftColumn = vertical.text.indexOf("学生")
        val rightColumn = vertical.text.indexOf("先生と生産")

        assertTrue("fixture did not recognize as expected\n$report", leftColumn >= 0)
        assertTrue("fixture did not recognize as expected\n$report", rightColumn >= 0)
        assertTrue(
            "ML Kit has started ordering 縦書き columns right-to-left. That is " +
                "correct, and it means stage 2's reorder may be redundant — " +
                "re-check V-10 before deleting anything.\n$report",
            leftColumn < rightColumn,
        )
    }

    /**
     * The column order is an **x-sort, not a y-sort**.
     *
     * This is the measurement that says the behaviour will never come right by
     * itself. In `sign-vertical-staggered.png` the right-hand column begins far
     * above the left-hand one, so anything ordering by vertical position would
     * emit it first. ML Kit still emits the left column first — it is applying a
     * horizontal-text reading order unconditionally.
     *
     * The same fixture also shows **elements splitting mid-column**: two columns
     * arrive as four elements. Nothing downstream may assume one element per
     * line.
     */
    @Test
    fun staggering_the_columns_does_not_change_the_order() {
        val result = recognize("sign-vertical-staggered.png")
        val report = dump("vertical-staggered", result)

        val rightColumnTop = result.elements.maxOf { it.box.left }
            .let { rightmost -> result.elements.filter { it.box.left >= rightmost - COLUMN_TOLERANCE } }
            .minOf { it.box.top }
        val leftColumnTop = result.elements.minOf { it.box.left }
            .let { leftmost -> result.elements.filter { it.box.left <= leftmost + COLUMN_TOLERANCE } }
            .minOf { it.box.top }

        assertTrue(
            "the fixture is meant to start the right column above the left one\n$report",
            rightColumnTop < leftColumnTop,
        )
        assertTrue(
            "expected the left column first despite starting lower\n$report",
            result.text.indexOf("学生") < result.text.indexOf("先生"),
        )
    }

    /**
     * Whatever the order, the offsets must address their own text — the same
     * invariant the horizontal test pins, checked on vertical input because the
     * fragmentation above is exactly the sort of thing that breaks it.
     */
    @Test
    fun vertical_element_offsets_address_their_own_text() {
        for (fixture in listOf("sign-vertical.png", "sign-vertical-staggered.png")) {
            val result = recognize(fixture)
            assertTrue("no elements were recorded for $fixture", result.elements.isNotEmpty())
            for (element in result.elements) {
                assertEquals(
                    "in $fixture, element ${element.text} does not sit at offset ${element.startOffset}",
                    element.text,
                    result.text.substring(element.startOffset, element.endOffset),
                )
            }
        }
    }

    private companion object {
        const val TAG = "VerticalTextOrder"

        /** Elements of one column share a left edge to within a few pixels. */
        const val COLUMN_TOLERANCE = 20
    }
}
